"""add success rate to historical routes

Revision ID: 8ba1ab35ad4e
Revises: 701289ab9d27
Create Date: 2026-06-04 07:57:33.735266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba1ab35ad4e'
down_revision: Union[str, Sequence[str], None] = '701289ab9d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_routes', sa.Column('historical_success_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historical_routes', 'historical_success_rate')
    # ### end Alembic commands ###
